#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : cpufetch
Version  : 1.04
Release  : 1
URL      : https://github.com/Dr-Noob/cpufetch/archive/refs/tags/v1.04.tar.gz
Source0  : https://github.com/Dr-Noob/cpufetch/archive/refs/tags/v1.04.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: cpufetch-bin = %{version}-%{release}
Requires: cpufetch-data = %{version}-%{release}
Requires: cpufetch-license = %{version}-%{release}
Requires: cpufetch-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center"><img width=50% src="./pictures/cpufetch.png"></p>
<h4 align="center">Simple yet fancy CPU architecture fetching tool</h4>

%package bin
Summary: bin components for the cpufetch package.
Group: Binaries
Requires: cpufetch-data = %{version}-%{release}
Requires: cpufetch-license = %{version}-%{release}

%description bin
bin components for the cpufetch package.


%package data
Summary: data components for the cpufetch package.
Group: Data

%description data
data components for the cpufetch package.


%package license
Summary: license components for the cpufetch package.
Group: Default

%description license
license components for the cpufetch package.


%package man
Summary: man components for the cpufetch package.
Group: Default

%description man
man components for the cpufetch package.


%prep
%setup -q -n cpufetch-1.04
cd %{_builddir}/cpufetch-1.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689241738
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1689241738
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cpufetch
cp %{_builddir}/cpufetch-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/cpufetch/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cpufetch

%files data
%defattr(-,root,root,-)
/usr/share/licenses/cpufetch-git/LICENSE

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cpufetch/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cpufetch.1.gz
